slam_toolbox:
  ros__parameters:

    use_sim_time: true

    # MODE
    mode: mapping   # we are doing localization

    # FRAMES
    map_frame: map
    odom_frame: odom
    base_frame: base_link

    # SCAN
    scan_topic: /world/default/model/x500_mono_cam_0/link/link/sensor/lidar_2d_v2/scan
    max_laser_range: 12.0

    # MAP
    resolution: 0.05

    # PERFORMANCE
    minimum_time_interval: 0.1
    transform_publish_period: 0.02

    # LOOP CLOSURE
    do_loop_closing: true