ekf_filter_node:
  ros__parameters:
    frequency: 20.0
    sensor_timeout: 0.1
    two_d_mode: false
 
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    publish_tf: true
    use_sim_time: true

    # ---------- IMU: Gazebo'dan (ros_gz_bridge) ----------
    imu0: "/world/default/model/x500_mono_cam_0/link/base_link/sensor/imu_sensor/imu"
    imu0_config: [
      false, false, false,   # x, y, z position
      true,  true,  true,    # roll, pitch, yaw
      false, false, false,   # linear vel
      true, true, true,    # yaw vel
      false, false, false    # accel
    ]
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    # ---------- ODOM: Sadece FMU'dan ----------
    odom0: "/odom/px4"
    odom0_config: [
      true,  true,  true,    # x, y, z position
      true,  true,  true,    # roll, pitch, yaw (orientation)
      true,  true,  true,    # linear velocity
      false, false, false,   # angular velocity (kullanmÄ±yoruz)
      false, false, false
    ]
    odom0_differential: false
    odom0_queue_size: 10